### PR TITLE
Introduce `SceneType` for ease and correctness

### PR DESCRIPTION
**Pull request by ubershmekel**
This PR

* Updates the Documentation
* Fixes a bug

Describe the changes below:

Introduce a new type `SceneType` that includes all things that could be a scene: `Phaser.Scene | Phaser.Types.Scenes.SettingsConfig | Phaser.Types.Scenes.CreateSceneFromObjectConfig | Function`.

Fix the bug where scenes could not be created from an array of `Phaser.Types.Scenes.SettingsConfig | Phaser.Types.Scenes.CreateSceneFromObjectConfig` in typecript.

I also threw in a warning in the parser so that folks know how to generate `types/phaser.d.ts`

This PR replaces https://github.com/photonstorm/phaser/pull/6235

### CODE REVIEW

**Comment by photonstorm** [comment]
Thanks for this. Please could you remove `Parser.js`, `Parser.map.js`, and `phaser.d.ts` from the PR, then I can merge it in 👍

**Comment by ubershmekel** [comment]
Woops! I renamed the branch on my repo which caused the PR to close. Sorry about that. Reopening

**Comment by ubershmekel** [comment]
There. Should be good to go.

**Comment by photonstorm** [comment]
👍

**Pull request merged**
