### PR TITLE
fix type definitions for Matter CollisionActiveEvent | CollisionStartEvent | CollisionEnd

### PR DESCRIPTION
**Pull request by hatchling13**
Please do not update the README or Change Log, we will do this when we merge your PR.

This PR
* Fixes a bug

Describe the changes below:
- Edit JSDocs according to [this comment](https://github.com/phaserjs/phaser/pull/6936#issuecomment-2447058392)
- Generate typedefs with `npm run tsgen`, tested with `npm run test-ts`

### CODE REVIEW

**Comment by photonstorm** [comment]
Happy to merge this, but please remove the package-lock and types builds first.

**Comment by hatchling13** [comment]
I assume that I have to revert changes caused by the typedef generating step(according to "remove"), am I right?

**Comment by photonstorm** [comment]
yes (and package-lock from npm i)

**Comment by hatchling13** [comment]
Yep! As you can see in the Changes section, I removed those in the following commit.

**Comment by photonstorm** [comment]
👍

**Pull request merged**
