### PR TITLE
Add methods to clear EmitZone or DeathZone

### PR DESCRIPTION
**Pull request by rexrainbow**
Please do not update the README or Change Log, we will do this when we merge your PR.

This PR (delete as applicable)

* Adds a new feature

Describe the changes below:

Add methods to clear EmitZone or DeathZone

### CODE REVIEW

**Comment by photonstorm** [comment]
Hmm, do we really need this along with `removeDeathZone` and `removeEmitZone` that we already have?

**Comment by rexrainbow** [comment]
`removeDeathZone`, `removeEmitZone` require a zone object as parameter, it is not easy/directly to remove all zones. 
I use `emitter.emitZones.length = 0` in my test code. So I guess that it is nice to have clear method, or invoking `removeDeathZone`, `removeEmitZone` without no parameter to clear all zones is a good solution, too.

**Comment by photonstorm** [comment]
👍

**Comment by photonstorm** [comment]
Merged, but renamed to be plural.

**Pull request merged**
