### PR TITLE
Add Phaser.Loader.LoaderPlugin#removePack

### LINKED ISSUE #6791: Unload asset pack
The loader plugin can currently load all assets from an asset-pack via `scene.load.pack(...)`, but it lacks the functionality for unloading an asset-pack.

Since the `pack` function must already have the code to read and iterate through assets in an asset-pack, maybe something like `scele.load.unloadAssetPack(...)` can be easy to implement, as it would just have to call `destroy` instead of `load` for each asset in the asset-pack.

Motivation:
Building multi-scene games for mobile with lots of assets can be difficult to do without this, as it requires the developer to track every asset it loads and manually and individually unload it when needed. This is almost like managing an asset-pack manually and it kind of defeats the purpose of the builtin asset-pack.
Pretty much all game engines support something along the lines of `unload unused assets` or `unload asset bundle` or `unload scene (which also unloads the assets)`.

### PR DESCRIPTION
**Pull request by samme**
This PR

* Adds a new feature (closes #6791)

> Remove the resources listed in an Asset Pack.
> 
> This removes Animations from the Animation Manager, Textures from the Texture Manager, and all other assets from their respective caches. It doesn't remove the Pack itself from the JSON cache, if it exists there. If the Pack includes another Pack, its resources will be removed too.

### CODE REVIEW

**Comment by tibimunteanu** [comment]
What is different for Spine assets? Are they managed by the Spine runtime?

**Comment by samme** [comment]
It's `add.spine()` that adds to the "spineTextures" cache and the Texture Manager, and the Spine plugins prefix texture keys differently. So maybe the plugins could handle this better.

**Comment by samme** [comment]
Now removes all Spine assets.

**Comment by tibimunteanu** [comment]
Nice! When can we expect this to be merged?

**Comment by zekeatchan** [comment]
Hi @samme. Thanks for submitting this pull request. We have implemented this and merged it with the `master` branch. It will be part of the next release.

**Pull request merged**
