### PR TITLE
Improve stable sort performance

### PR DESCRIPTION
**Pull request by JernejHabjan**
This PR

* Improves performance

[Issue created here](https://github.com/photonstorm/phaser/pull/6216). I'm not sure if this is ok solution, but simple array.sort could be used

### CODE REVIEW

**Comment by photonstorm** [comment]
This may need putting behind a Game Config flag because Array sort is unstable on lots of older browsers, and without a stable sort, it causes all kinds of rendering errors on the likes of IE.

**Comment by JernejHabjan** [comment]
@photonstorm not sure how to proceed here - created additional commit, but not sure this is the right way

**Comment by photonstorm** [comment]
Leave this with me - I think we can switch this flag automatically if, for example, we detect IE vs. Chrome. Plus, I can't merge it because the PR contains files that shouldn't be updated :) (like the TS defs). But I'll have a play with this now, as I think we can use it somehow.

**Comment by photonstorm** [comment]
Ok, this feature is now in the master branch (and enabled based on browser detection), so worth you re-testing your previous demos, please.

**Comment by JernejHabjan** [comment]
Commented the perf improvement on issue

**Pull request closed without merging**
