### PR TITLE
Fix `createFromObjects()` from Tiled array of object custom properties

### LINKED ISSUE #6391: `createFromObjects()` doesn't copy custom properties
## Version

* Phaser Version: 3.60.0-beta.18

## Description

> For example giving an Object a property of `alpha: 0.5` in Tiled will be reflected in the Game Object that is created.

This happened in v3.55.2 but it doesn't happen now. 

## Example Test Code

<https://labs.phaser.io/edit.html?src=src/3.60\tilemap\create%20from%20objects.js&v=3.60.0-beta.18>

```js
const coinObject = this.map.objects[0].objects[3];

console.assert(coinObject.properties.alpha === 0.25);

const [ coin ] = this.map.createFromObjects('Coin Object Layer', [
    { id: coinObject.id, key: 'coin' }
]);

console.assert(coin.alpha === 0.25, 'Coin sprite should have alpha 0.25 not %s', coin.alpha);
```

### PR DESCRIPTION
**Pull request by samme**
This PR

* Fixes a bug

Fixes #6391

### CODE REVIEW

**Comment by paxperscientiam** [comment]
Any idea when this will get merged?

**Comment by samme** [comment]
No, but you can [build Phaser](https://github.com/photonstorm/phaser#building-from-source) from this commit, or I can do it later.

**Comment by samme** [comment]
@paxperscientiam [phaser-build.zip](https://github.com/photonstorm/phaser/files/11605161/phaser-build.zip)

**Comment by photonstorm** [comment]
👍

**Pull request merged**
