### PR TITLE
EmitterOpRandomMinMaxConfig type correction

### PR DESCRIPTION
**Pull request by AlvaroEstradaDev**
Added the description of the "int" boolean property that was missing

### CODE REVIEW

**Comment by samme** [comment]
Shouldn't it be

> If true, only integers are selected from the range

or something similar?

**Comment by AlvaroEstradaDev** [comment]
> Shouldn't it be
> 
> > If true, only integers are selected from the range
> 
> or something similar?

I took "EmitterOpRandomStartEndConfig.js" description of random as reference.

**Comment by samme** [comment]
But that's completely different. Here `int: true` means force the random value to be an integer.

**Comment by AlvaroEstradaDev** [comment]
> But that's completely different. Here `int: true` means force the random value to be an integer.

Oh, yeah, I misread the code. I'm gonna change it.

**Comment by photonstorm** [comment]
👍

**Pull request merged**
