### PR TITLE
replace phaser3spectorjs with spectorjs

### PR DESCRIPTION
**Pull request by hajirasyafi**
Please do not update the README or Change Log, we will do this when we merge your PR.

This PR (delete as applicable)

* Fixes a bug

Describe the changes below:
i'm sorry about this. this due bugs when using phaser with nextjs 13.

`Module not found: Can't resolve 'phaser3spectorjs'`

as i know 'phaser3spectorjs' has the same source from 'spectorjs'
i've following all contributing guidlines

### CODE REVIEW

**Comment by samme** [comment]
> Module not found: Can't resolve 'phaser3spectorjs'

I've seen this, and I think it happens when bundlers load `src/phaser.js`.

Maybe `phaser3spectorjs` should be moved from `devDependencies` to `dependencies`.

You can solve the error with

    npm install phaser3spectorjs

**Comment by hajirasyafi** [comment]
> > Module not found: Can't resolve 'phaser3spectorjs'
> 
> I've seen this, and I think it happens when bundlers load `src/phaser.js`.
> 
> Maybe `phaser3spectorjs` should be moved from `devDependencies` to `dependencies`.
> 
> You can solve the error with
> 
> ```
> npm install phaser3spectorjs
> ```

Yes I knew if run : `npm install phaser3spectorjs` it will solved the problem. I also trying to solve the problem by making changes, and make PR. so, should I close this PR?
I've tested replacing phaser3spector with spectorjs, and works fine.

**Comment by photonstorm** [comment]
If I merge this it will break SpectorGL. We had to use our own fork for a reason. I'm happy to move dependencies location though.

**Comment by hajirasyafi** [comment]
Oh, sorry about that, I'll close this PR.

**Pull request closed without merging**
