### PR TITLE
add "aac" sound type support

### PR DESCRIPTION
**Pull request by Ariorh1337**
Please do not update the README or Change Log, we will do this when we merge your PR.

This PR (delete as applicable)

* Adds a new feature

Describe the changes below:
Adding "aac" audio format support

### CODE REVIEW

**Comment by samme** [comment]
Needs a JSDoc `@property`.

**Comment by photonstorm** [comment]
Thanks for your PR, but this feature is already tested for under the `Audio.m4a` property.

**Comment by Ariorh1337** [comment]
> but this feature is already tested for under the `Audio.m4a` property

you are right, but files with aac format are not available for download due to an exception, this pr resolves the exception and makes it possible to use files with aac format

**Comment by photonstorm** [comment]
> you are right, but files with aac format are not available for download due to an exception, this pr resolves the exception and makes it possible to use files with aac format

What exception exactly? On Safari on my Mac `Audio.m4a` is `true`, which would allow me to load an aac file.

**Comment by Ariorh1337** [comment]
aac format is also `example.aac` files [Wikipedia](https://en.wikipedia.org/wiki/Advanced_Audio_Coding#Container_formats)
to be able to load them needs current PR, otherwise loader doesnot want to get load it
image

**Comment by samme** [comment]
```js
this.load.video('example', { url: 'example.aac', type: 'mp4' });
```

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.

**Pull request closed without merging**
